a:
  build: ./sample_web_server
  ports:
    - "81:80"

b:
  build: ./sample_web_server
  ports:
    - "82:80"

nginx:
  image: nginx:1.10.1
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - a
    - b
  ports:
    - "80:80"
